# Exemplo de arquivo de secrets para o Streamlit
# Copie este arquivo para secrets.toml e configure suas chaves

# OpenAI API Key (obrigatória)
OPENAI_API_KEY = "sk-your-openai-api-key-here"

# Outras configurações opcionais
# MODEL_NAME = "gpt-4o"
# RETRIEVAL_SEARCH_TYPE = "mmr"
# RETRIEVAL_KARGS = {"k": 5, "fetch_k": 20}
